### ISSUE TITLE
Null Reference error when running MapImporter.BeginReadAsync(RecordPositions)

### ISSUE THREAD

**Issue by Astuce-Julian** [DekuDesu/UnityShapefileAsync#4]
Hi, I am really interested in this plugin and looks VERY promising but I am running into a null reference error when trying to import using the MapImporter BeginReadAsync function. This is the error I receive:

```
System.NullReferenceException: Object reference not set to an instance of an object
  at PSS.Mapping.CSVReader.Cancel () [0x00008] in C:\Users\Astuce\Desktop\Software\Experimentation\UnityTests\ShapefilePluginTesting\Assets\ShapeFileImporter\Map\Importing\CSV\CSVReader.cs:158 
  at PSS.Mapping.MapImporter.Cancel () [0x0000d] in C:\Users\Astuce\Desktop\Software\Experimentation\UnityTests\ShapefilePluginTesting\Assets\ShapeFileImporter\Map\Importing\Map\MapImporter.cs:81 
  at PSS.Mapping.MapImporter+<BeginReadingAsync>d__32.MoveNext () [0x001d3] in C:\Users\Astuce\Desktop\Software\Experimentation\UnityTests\ShapefilePluginTesting\Assets\ShapeFileImporter\Map\Importing\Map\MapImporter.cs:120 
```

This seems to only happen when I try to await that Task.
I have RecordPositions set to 0,3,5 and will attach the csv and shp files for reference. 
Any assistance would be awesome.
Cheers!
[Reference.zip](https://github.com/DekuDesu/UnityShapefileAsync/files/7809522/Reference.zip)

PS is this tied to the issue you have open? And if so is there a work around you can suggest until a fix is done.

**Comment by artyredd** [comment]
I went ahead and took a look for you. This project is deprecated at this point, I no longer recommend using this library.

To be absolutely transparent, this library abused Unity's task scheduler for more performance and since then Unity has updated how Task's are executed on other threads and limited how much concurrency we can have. As such this library doesn't work. That's a good thing since it's hot garbage.

I went ahead and created a work around for you though. This should work:

```csharp
ShapeFileReader reader = new ShapeFileReader("US_States.shp");

reader.BeginReadingAsync();

while (reader.Status != TaskStatus.RanToCompletion)
{
    continue;
}

CSVReader otherReader = Factory.CreateCSVReader("US_States.csv");

otherReader.ReadCSV(0, 3, 5);

var positions = new RecordPositions(0, 3, 5);

using (var writer = new StreamWriter(File.OpenWrite("US_States.json")))
{
    while (reader.Records.TryDequeue(out IMapData data))
    {
        while (otherReader.LineQueue.TryDequeue(out string line))
        {
            writer.WriteLine(Factory.CreateMapRecord(data, line.Split(','), positions).Serialize());
        }
    }
}
```

**Comment by artyredd** [comment]
Added work around, see 8901a3e, 9595909
